package io.github.adomasdauda.client.constants;


public enum NotPlacableBlockKeys {

    item_minecraft_wooden_axe,
    item_minecraft_stone_axe,
    item_minecraft_iron_axe,
    item_minecraft_golden_axe,
    item_minecraft_diamond_axe,
    item_minecraft_netherite_axe,
    item_minecraft_wooden_pickaxe,
    item_minecraft_stone_pickaxe,
    item_minecraft_iron_pickaxe,
    item_minecraft_golden_pickaxe,
    item_minecraft_diamond_pickaxe,
    item_minecraft_netherite_pickaxe,
    item_minecraft_wooden_shovel,
    item_minecraft_stone_shovel,
    item_minecraft_iron_shovel,
    item_minecraft_golden_shovel,
    item_minecraft_diamond_shovel,
    item_minecraft_netherite_shovel,
    item_minecraft_wooden_hoe,
    item_minecraft_stone_hoe,
    item_minecraft_iron_hoe,
    item_minecraft_golden_hoe,
    item_minecraft_diamond_hoe,
    item_minecraft_netherite_hoe,
    item_minecraft_wooden_sword,
    item_minecraft_stone_sword,
    item_minecraft_iron_sword,
    item_minecraft_golden_sword,
    item_minecraft_diamond_sword,
    item_minecraft_netherite_sword,
    item_minecraft_bow,
    item_minecraft_crossbow,
    item_minecraft_fishing_rod,
    item_minecraft_carrot_on_a_stick,
    item_minecraft_shears,
    item_minecraft_flint_and_steel,
    item_minecraft_shield,
    item_minecraft_elytra,
    item_minecraft_trident,
    item_minecraft_snowball,
    item_minecraft_egg,
    item_minecraft_ender_pearl,
    item_minecraft_experience_bottle,
    item_minecraft_potion,
    item_minecraft_splash_potion,
    item_minecraft_lingering_potion,
    item_minecraft_tipped_arrow,
    item_minecraft_firework_rocket,
    item_minecraft_firework_star,
    item_minecraft_enchanted_book,
    item_minecraft_writable_book,
    item_minecraft_written_book,
    item_minecraft_map,
    item_minecraft_suspicious_stew,
    item_minecraft_totem_of_undying,
    item_minecraft_air,

    // add mob drops too

    item_minecraft_leather,
    item_minecraft_iron_ingot,
    item_minecraft_gold_ingot,
    item_minecraft_diamond,
    item_minecraft_netherite_ingot,
    item_minecraft_bone,
    item_minecraft_string,
    item_minecraft_feather,
    item_minecraft_gunpowder,
    item_minecraft_slime_ball,
    item_minecraft_ghast_tear,
    item_minecraft_blaze_rod,
    item_minecraft_magma_cream,
    item_minecraft_ender_eye,
    item_minecraft_nether_star,
    item_minecraft_pufferfish,
    item_minecraft_salmon,
    item_minecraft_cooked_salmon,
    item_minecraft_clownfish,
    item_minecraft_tropical_fish,
    item_minecraft_cod,
    item_minecraft_cooked_cod,
    item_minecraft_ink_sac,
    item_minecraft_cocoa_beans,
    item_minecraft_lapis_lazuli,
    item_minecraft_redstone,
    item_minecraft_glowstone_dust,
    item_minecraft_rabbit_foot,
    item_minecraft_rabbit_hide,
    item_minecraft_leather_horse_armor,
    item_minecraft_iron_horse_armor,
    item_minecraft_golden_horse_armor,
    item_minecraft_diamond_horse_armor,
    item_minecraft_netherite_horse_armor,
    item_minecraft_saddle,
    item_minecraft_name_tag,
    item_minecraft_lead,
    item_minecraft_iron_nugget;

    public static boolean contains(String inputTranslationKey) {
        for (NotPlacableBlockKeys translationKey : NotPlacableBlockKeys.values()) {
            if (translationKey.name().replace("_", ".").equals(inputTranslationKey)) {
                return true;
            }
        }
        return false;
    }
}
